name: no-mpi

on:
  push:
    branches:
      - master
      - spn
      - testci

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: ./.github/actions/runtests
      with:
        dir: Algebra
        mpi: -no-mpi
        nc: 2
        repr: FUND
        ecsw: -no-expclover
